/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parley;

import parley.ecs.components.AI;
import parley.ecs.components.Player;
import parley.ecs.components.PhysicalObject;
import parley.ecs.core.Engine;
import parley.systems.AIMovement;
import parley.systems.PlayerMovement;
import parley.systems.UI;


public class App {
    public static void main(String[] args) throws InterruptedException {
        Engine engine = new Engine();

        engine.newEntity()
                .with(new PhysicalObject('@', 50, 11))
                .with(new Player())
                .build();

        engine.newEntity()
                .with(new PhysicalObject('+', 40, 32))
                .with(new AI())
                .build();

        engine.newEntity()
                .with(new PhysicalObject('-', 40, 32))
                .with(new AI())
                .build();

        for (int i = 10; i <= 70; ++i) {
            engine.newEntity()
                    .with(new PhysicalObject('#', i, 20))
                    .build();
        }

        Inputs.startService();
        UI.start(engine);
        runEventLoop(engine);
    }

    private static void runEventLoop(Engine engine) throws InterruptedException {
        PlayerMovement movement = new PlayerMovement();
        AIMovement aiMovement = new AIMovement();

        while (true) {
            engine.runSystem(movement);
            engine.runSystem(aiMovement);

            Thread.sleep(100);
        }
    }
}
